<a href="https://colab.research.google.com/github/DoctaSTEPHEN/CPE313/blob/main/Discussion_5_2_Regular_Expression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [119]:
import pandas as pd

twitter = pd.read_csv("/content/drive/MyDrive/CPE 313/twitter_training.csv", header=None)
twitter.columns = ["Tweet_ID", "Entity", "Sentiment", "Tweet_content"]
twitter.head()

,Tweet_ID,Entity,Sentiment,Tweet_content
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [120]:
import re

twitter['word_count'] = twitter['Tweet_content'].apply(lambda text: len(re.findall(r"on", str(text))))
twitter['char_count'] = twitter['Tweet_content'].apply(lambda text: len(re.findall(r"\,", str(text))))
twitter['num_count'] = twitter['Tweet_content'].apply(lambda text: len(re.findall(r"\w*3\b", str(text))))

In [124]:
twitter.head()

,Tweet_ID,Entity,Sentiment,Tweet_content,word_count,char_count,num_count
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...,1,1,0
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...,0,1,0
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...,1,1,0
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...,1,1,0
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...,1,1,0

In [121]:
print(f'Total occurrences of "on": {twitter["word_count"].sum()}')
print(f'Total commas (,): {twitter["char_count"].sum()}')
print(f'Total occurrences of number "3": {twitter["num_count"].sum()}')

Total occurrences of "on": 72117
Total commas (,): 32037
Total occurrences of number "3": 4321

In [122]:
URL_find = twitter['Tweet_content'].apply(lambda text: re.findall(r"\S+/\S+", str(text)))
URL = URL_find[URL_find.astype(bool)]
URL.head()

6     [pic.twitter.com/mLsI5wf9Jg]
9     [pic.twitter.com/mLsI5wf9Jg]
10    [pic.twitter.com/mLsI5wf9Jg]
12                [dlvr.it/RMTrgF]
15                [dlvr.it/RMTrgF]
Name: Tweet_content, dtype: object